# Generated by Django 3.2.12 on 2022-07-17 19:22

from django.db import migrations, models
import django.db.models.deletion
import drivers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriversModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PESEL', models.CharField(max_length=11, unique=True, validators=[drivers.models.PESEL_walidator])),
                ('firstname', models.CharField(max_length=32, verbose_name='imie')),
                ('lastname', models.CharField(max_length=32, verbose_name='nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='DriverCertificatesModel',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certyficate', serialize=False, to='drivers.driversmodel')),
                ('driver_licence_enddate', models.DateField(blank=True, null=True, verbose_name='Prawo Jazdy data koncowa')),
                ('B', models.BooleanField(default=True)),
                ('CE', models.BooleanField(default=True)),
                ('C', models.BooleanField(default=True)),
                ('BE', models.BooleanField(default=False)),
                ('C1', models.BooleanField(default=False)),
                ('kwalifikacja_data_konc', models.DateField(blank=True, null=True, verbose_name='Swiadectwo kwal. data koncowa')),
                ('ADR_data_konc', models.DateField(blank=True, null=True, verbose_name='ADR data koncowa')),
                ('ADR_cat1', models.BooleanField(default=False, verbose_name='kat 1')),
                ('ADR_cat7', models.BooleanField(default=False, verbose_name='kat 7')),
            ],
        ),
    ]
