# Generated by Django 3.2.12 on 2022-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversmodel',
            name='PESEL',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='driversmodel',
            name='firstname',
            field=models.CharField(max_length=32, verbose_name='imie'),
        ),
        migrations.AlterField(
            model_name='driversmodel',
            name='hiring_date',
            field=models.DateField(null=True, verbose_name='data zatrudnienia'),
        ),
        migrations.AlterField(
            model_name='driversmodel',
            name='lastname',
            field=models.CharField(max_length=32, verbose_name='nazwisko'),
        ),
    ]
