# Generated by Django 3.2.12 on 2022-07-01 18:17

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20220701_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversmodel',
            name='PESEL',
            field=models.CharField(max_length=11, unique=True, validators=[drivers.models.PESEL_walidator]),
        ),
    ]
