# Generated by Django 3.2.12 on 2022-07-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driversmodel_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversmodel',
            name='hiring_date',
        ),
    ]
