# Generated by Django 3.2.12 on 2022-07-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driversmodel_hiring_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCertificatesModel',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='certyficate', serialize=False, to='drivers.driversmodel')),
                ('driver_licence_enddate', models.DateField(verbose_name='Prawo Jazdy data koncowa')),
                ('B', models.BooleanField(default=True)),
                ('CE', models.BooleanField(default=True)),
                ('C', models.BooleanField(default=True)),
                ('BE', models.BooleanField(default=False)),
                ('C1', models.BooleanField(default=False)),
                ('kwalifikacja_data_konc', models.DateField(verbose_name='Swiadectwo kwal. data koncowa')),
                ('ADR_data_konc', models.DateField(verbose_name='ADR data koncowa')),
                ('ADR_cat1', models.BooleanField(default=False, verbose_name='kat 1')),
                ('ADR_cat7', models.BooleanField(default=False, verbose_name='kat 7')),
            ],
        ),
    ]
