# Generated by Django 3.2.12 on 2022-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20220705_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercertificatesmodel',
            name='ADR_data_konc',
            field=models.DateField(null=True, verbose_name='ADR data koncowa'),
        ),
        migrations.AlterField(
            model_name='drivercertificatesmodel',
            name='driver_licence_enddate',
            field=models.DateField(null=True, verbose_name='Prawo Jazdy data koncowa'),
        ),
        migrations.AlterField(
            model_name='drivercertificatesmodel',
            name='kwalifikacja_data_konc',
            field=models.DateField(null=True, verbose_name='Swiadectwo kwal. data koncowa'),
        ),
    ]
