# Generated by Django 3.2.12 on 2022-07-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ciągnik siodłowy', 'ciągnik siodłowy'), ('samochód ciężarowy firana', 'samochód ciężarowy firana'), ('samochód ciężarowy wywrotka 3-4 osie.', 'samochód ciężarowy wywrotka 3-4 osie'), ('samochód ciężarowy tandem', 'samochód ciężarowy tandem'), ('przyczepa 2 osie', 'przyczepa 2 osie'), ('przyczepa tandem firana', 'przyczepa tandem firana'), ('naczepa firana', 'naczepa firana'), ('naczepa firana low deck', 'naczepa firana low deck'), ('naczepa plandeka burty', 'naczepa plandeka burty'), ('naczepa platforma', 'naczepa platforma'), ('naczepa szkielet.kontener BDF', 'naczepa szkielet.kontener BDF'), ('naczepa samowyładowcza walking-floor', 'naczepa samowyładowcza walking-floor'), ('naczepa wywrotka', 'naczepa wywrotka'), ('naczepa silos', 'naczepa silos'), ('naczepa cysterna ciecz', 'naczepa cysterna ciecz'), ('naczepa cysterna gaz', 'naczepa cysterna gaz'), ('naczepa cysterna paszowóz', 'naczepa cysterna paszowóz'), ('naczepa laweta niskopodwoz.', 'naczepa laweta niskopodwoz.'), ('naczepa chłodnia', 'naczepa chłodnia'), ('naczepa izoterma', 'naczepa izoterma')], max_length=64)),
                ('marka', models.CharField(choices=[('DAF', 'DAF'), ('MAN', 'MAN'), ('VOLVO', 'VOLVO'), ('SCANIA', 'SCANIA'), ('IVECO', 'IVECO'), ('RENAULT', 'RENAULT'), ('MERCEDES', 'MERCEDES'), ('Krone', 'Krone'), ('Schwartzmüller', 'Schwartzmüller'), ('Schmitz', 'Schmitz'), ('Wielton', 'Wielton'), ('Mega', 'Mega'), ('Kassbohrer', 'Kassbohrer'), ('Kögel', 'Kögel'), ('inne', 'inne')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('VIN', models.CharField(max_length=17, unique=True)),
                ('nr_rej', models.CharField(max_length=8, unique=True, verbose_name='nr rej.')),
                ('rok_prod', models.PositiveSmallIntegerField(choices=[(2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984')], verbose_name='rok produkcji')),
                ('truck', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePermitsAndDedlinesModel',
            fields=[
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='vehicles.vehiclesmodel')),
                ('badanietechniczne_nazwa', models.CharField(default='Przegląd techniczy pojazdu', max_length=32)),
                ('badanietechniczne_instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40, null=True)),
                ('badanietechniczne_wymagane', models.BooleanField(default=True)),
                ('badanietechniczne_data_konc', models.DateField(null=True)),
                ('tachograf_nazwa', models.CharField(default='Przegląd tachografu', max_length=60)),
                ('tachograf_instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40)),
                ('tachograf_wymagane', models.BooleanField(default=False)),
                ('tachograf_data_konc', models.DateField(blank=True, null=True)),
                ('ADR_nazwa', models.CharField(default='Dopuszczenie do przewodu ADR', max_length=32)),
                ('ADR_instytucja', models.CharField(default='TDT', max_length=40)),
                ('ADR_wymagane', models.BooleanField(default=False)),
                ('ADR_data_konc', models.DateField(blank=True, null=True)),
                ('euro_norma', models.CharField(choices=[('Euro 7', 'Euro 7'), ('Euro 6', 'Euro 6'), ('Euro 5', 'Euro 5'), ('Euro 4', 'Euro 4'), ('Euro 3', 'Euro 3'), ('Euro 2', 'Euro 2'), ('Euro 1', 'Euro 1'), ('Euro 0', 'Euro 0'), ('N49', 'N49'), ('nie dotyczy', 'nie dotyczy')], default='nie dotyczy', max_length=12, null=True)),
                ('euro_wymagane', models.BooleanField(default=False)),
                ('FRC_nazwa', models.CharField(default='Badanie termiczne chłodni ATP/FRC', max_length=32)),
                ('FRC_instytucja', models.CharField(default='Politechnika Poznańska, IMRiPS', max_length=40, null=True)),
                ('FRC_wymagane', models.BooleanField(default=False)),
                ('FRC_data_konc', models.DateField(blank=True, null=True)),
                ('UDT_nazwa', models.CharField(default='Badanie dopuszczenia windy hydraulicznej lub HDS', max_length=60)),
                ('UDT_instytucja', models.CharField(default='Urząd Dozoru Techniczego', max_length=40)),
                ('UDT_wymagane', models.BooleanField(default=False)),
                ('UDT_data_konc', models.DateField(blank=True, null=True)),
                ('TDT_nazwa', models.CharField(default='Dozór zbiorników', max_length=64)),
                ('TDT_instytucja', models.CharField(default='Transportowy Dozór Techniczny', max_length=40)),
                ('TDT_wymagane', models.BooleanField(default=False)),
                ('TDT_data_konc', models.DateField(blank=True, null=True)),
                ('Ubezpieczeniakom_instytucja', models.CharField(default='Zakład Ubezpieczeń', max_length=72, null=True)),
                ('Ubezpieczeniakom_OC', models.BooleanField(default=True)),
                ('Ubezpieczeniakom_AC', models.BooleanField(default=False)),
                ('Ubezpieczeniakom_NNW', models.BooleanField(default=False)),
                ('Ubezpieczeniakom_data_konc', models.DateField(blank=True, null=True)),
                ('Ubezpieczeniakom_nr_polisy', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
