# Generated by Django 3.2.12 on 2022-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ciągnik siodłowy', 'ciągnik siodłowy'), ('samochód ciężarowy firana', 'samochód ciężarowy firana'), ('samochód ciężarowy wywrotka 3-4 osie.', 'samochód ciężarowy wywrotka 3-4 osie'), ('samochód ciężarowy tandem', 'samochód ciężarowy tandem'), ('przyczepa 2 osie', 'przyczepa 2 osie'), ('przyczepa tandem firana', 'przyczepa tandem firana'), ('naczepa firana', 'naczepa firana'), ('naczepa firana low deck', 'naczepa firana low deck'), ('naczepa plandeka burty', 'naczepa plandeka burty'), ('naczepa platforma', 'naczepa platforma'), ('naczepa szkielet.kontener BDF', 'naczepa szkielet.kontener BDF'), ('naczepa samowyładowcza walking-floor', 'naczepa samowyładowcza walking-floor'), ('naczepa wywrotka', 'naczepa wywrotka'), ('naczepa silos', 'naczepa silos'), ('naczepa cysterna ciecz', 'naczepa cysterna ciecz'), ('naczepa cysterna gaz', 'naczepa cysterna gaz'), ('naczepa cysterna paszowóz', 'naczepa cysterna paszowóz'), ('naczepa laweta niskopodwoz.', 'naczepa laweta niskopodwoz.'), ('naczepa chłodnia', 'naczepa chłodnia'), ('naczepa izoterma', 'naczepa izoterma')], max_length=64)),
                ('marka', models.CharField(choices=[('DAF', 'DAF'), ('MAN', 'MAN'), ('VOLVO', 'VOLVO'), ('SCANIA', 'SCANIA'), ('IVECO', 'IVECO'), ('RENAULT', 'RENAULT'), ('MERCEDES', 'MERCEDES'), ('Krone', 'Krone'), ('Schwartzmüller', 'Schwartzmüller'), ('Schmitz', 'Schmitz'), ('Wielton', 'Wielton'), ('Mega', 'Mega'), ('Kassbohrer', 'Kassbohrer'), ('Kögel', 'Kögel'), ('inne', 'inne')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('VIN', models.CharField(max_length=17, unique=True)),
                ('nr_rej', models.CharField(max_length=8, unique=True, verbose_name='nr rej.')),
                ('rok_prod', models.PositiveSmallIntegerField(choices=[(2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996'), (1995, '1995'), (1994, '1994'), (1993, '1993'), (1992, '1992'), (1991, '1991'), (1990, '1990'), (1989, '1989'), (1988, '1988'), (1987, '1987'), (1986, '1986'), (1985, '1985'), (1984, '1984')], verbose_name='rok produkcji')),
                ('truck', models.BooleanField(default=True)),
            ],
        ),
    ]
