# Generated by Django 3.2.12 on 2022-06-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PojazdyModel',
            new_name='VehiclesModel',
        ),
    ]
