# Generated by Django 3.2.12 on 2022-07-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePermitsAndDedlinesModel',
            fields=[
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='vehicles.vehiclesmodel')),
                ('badanietechniczne_nazwa', models.CharField(default='Przegląd techniczy pojazdu', max_length=32)),
                ('badanietechniczne_instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40, null=True)),
                ('badanietechniczne_wymagane', models.BooleanField(default=True)),
                ('badanietechniczne_data_konc', models.DateField(null=True)),
                ('tachograf_nazwa', models.CharField(default='Przegląd tachografu', max_length=60)),
                ('tachograf_instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40)),
                ('tachograf_wymagane', models.BooleanField(default=False)),
                ('tachograf_data_konc', models.DateField(blank=True, null=True)),
                ('ADR_nazwa', models.CharField(default='Dopuszczenie do przewodu ADR', max_length=32)),
                ('ADR_instytucja', models.CharField(default='TDT', max_length=40)),
                ('ADR_wymagane', models.BooleanField(default=False)),
                ('ADR_data_konc', models.DateField(blank=True, null=True)),
                ('euro_norma', models.CharField(choices=[('Euro 7', 'Euro 7'), ('Euro 6', 'Euro 6'), ('Euro 5', 'Euro 5'), ('Euro 4', 'Euro 4'), ('Euro 3', 'Euro 3'), ('Euro 2', 'Euro 2'), ('Euro 1', 'Euro 1'), ('Euro 0', 'Euro 0'), ('N49', 'N49'), ('nie dotyczy', 'nie dotyczy')], default='nie dotyczy', max_length=12, null=True)),
                ('euro_wymagane', models.BooleanField(default=False)),
                ('FRC_nazwa', models.CharField(default='Badanie termiczne chłodni ATP/FRC', max_length=32)),
                ('FRC_instytucja', models.CharField(default='Politechnika Poznańska, IMRiPS', max_length=40, null=True)),
                ('FRC_wymagane', models.BooleanField(default=False)),
                ('FRC_data_konc', models.DateField(blank=True, null=True)),
                ('UDT_nazwa', models.CharField(default='Badanie dopuszczenia windy hydraulicznej lub HDS', max_length=60)),
                ('UDT_instytucja', models.CharField(default='Urząd Dozoru Techniczego', max_length=40)),
                ('UDT_wymagane', models.BooleanField(default=False)),
                ('UDT_data_konc', models.DateField(blank=True, null=True)),
                ('TDT_nazwa', models.CharField(default='Dozór zbiorników', max_length=64)),
                ('TDT_instytucja', models.CharField(default='Transportowy Dozór Techniczny', max_length=40)),
                ('TDT_wymagane', models.BooleanField(default=False)),
                ('TDT_data_konc', models.DateField(blank=True, null=True)),
                ('Ubezpieczeniakom_instytucja', models.CharField(default='Zakład Ubezpieczeń', max_length=72, null=True)),
                ('Ubezpieczeniakom_OC', models.BooleanField(default=True)),
                ('Ubezpieczeniakom_AC', models.BooleanField(default=False)),
                ('Ubezpieczeniakom_NNW', models.BooleanField(default=False)),
                ('Ubezpieczeniakom_data_konc', models.DateField(blank=True, null=True)),
                ('Ubezpieczeniakom_nr_polisy', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
