# Generated by Django 3.2.12 on 2022-06-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_pojazdymodel_vehiclesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BT',
            fields=[
                ('nazwa', models.CharField(default='Przegląd techniczy pojazdu', max_length=32)),
                ('instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40, null=True)),
                ('wymagane', models.BooleanField(default=True)),
                ('data_konc', models.DateField(null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='przegladtech', serialize=False, to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
