# Generated by Django 3.2.12 on 2022-06-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclepermitsanddedlinesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepermitsanddedlinesmodel',
            name='pojazd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='VehicleDetails', serialize=False, to='vehicles.vehiclesmodel'),
        ),
    ]
