# Generated by Django 3.2.12 on 2022-06-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_bt'),
    ]

    operations = [
        migrations.CreateModel(
            name='tacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Przegląd tachografu', max_length=60)),
                ('instytucja', models.CharField(default='Okręgowa Stacja Kontroli Pojazdów', max_length=40)),
                ('wymagane', models.BooleanField(default=False)),
                ('data_konc', models.DateField(blank=True, null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='przegladtacho', to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
