# Generated by Django 3.2.12 on 2022-06-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_tacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('nazwa', models.CharField(default='Dopuszczenie do przewodu ADR', max_length=32)),
                ('instytucja', models.CharField(default='TDT', max_length=40)),
                ('wymagane', models.BooleanField(default=False)),
                ('data_konc', models.DateField(blank=True, null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='przegladadr', serialize=False, to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
