# Generated by Django 3.2.12 on 2022-06-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehiclepermitsanddedlinesmodel_pojazd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclepermitsanddedlinesmodel',
            old_name='trachograf_data_konc',
            new_name='tachograf_data_konc',
        ),
    ]
