# Generated by Django 3.2.12 on 2022-06-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_normaczystoscispalin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRC',
            fields=[
                ('nazwa', models.CharField(default='Badanie termiczne chłodni ATP/FRC', max_length=32)),
                ('instytucja', models.CharField(default='Politechnika Poznańska, IMRiPS', max_length=40, null=True)),
                ('wymagane', models.BooleanField(default=False)),
                ('data_konc', models.DateField(blank=True, null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='przegladfrc', serialize=False, to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
