# Generated by Django 3.2.12 on 2022-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_uko'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesmodel',
            name='truck',
            field=models.BooleanField(default=True),
        ),
    ]
