# Generated by Django 3.2.12 on 2022-06-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehiclesmodel_truck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BT',
            new_name='BtModel',
        ),
    ]
