# Generated by Django 3.2.12 on 2022-06-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_rename_bt_btmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tacho',
            new_name='TachoModel',
        ),
    ]
