# Generated by Django 3.2.12 on 2022-06-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_rename_tacho_tachomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UKO',
        ),
    ]
