# Generated by Django 3.2.12 on 2022-06-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_delete_uko'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkoModel',
            fields=[
                ('instytucja', models.CharField(default='Zakład Ubezpieczeń', max_length=72, null=True)),
                ('OC', models.BooleanField(default=True)),
                ('AC', models.BooleanField(default=False)),
                ('NNW', models.BooleanField(default=False)),
                ('data_konc', models.DateField(blank=True, null=True)),
                ('nr_polisy', models.CharField(max_length=32, null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='komunikacyjne', serialize=False, to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
