# Generated by Django 3.2.12 on 2022-06-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_ukomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADR',
        ),
    ]
