# Generated by Django 3.2.12 on 2022-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_adrmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UDT',
        ),
    ]
