# Generated by Django 3.2.12 on 2022-06-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_delete_udt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdtModel',
            fields=[
                ('nazwa', models.CharField(default='Badanie dopuszczenia windy hydraulicznej lub HDS', max_length=60)),
                ('instytucja', models.CharField(default='Urząd Dozoru Techniczego', max_length=40)),
                ('wymagane', models.BooleanField(default=False)),
                ('data_konc', models.DateField(blank=True, null=True)),
                ('pojazd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='przegladudt', serialize=False, to='vehicles.vehiclesmodel')),
            ],
        ),
    ]
