# Generated by Django 3.2.12 on 2022-06-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_frcmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TDT',
        ),
    ]
